/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazgraficametodos;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Héctor
 */
public class PanelNewton extends javax.swing.JPanel {

    /**
     * Creates new form PanelNewton
     */
    private static int m;
    String ecuacion = "";
    private static Ecuacion F = new Ecuacion();

    public PanelNewton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        textFieldNoPuntos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        textFieldValorX = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        X = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        textFieldResultado = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Delta = new javax.swing.JTable();
        textFieldFuncion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Y = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        SG = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        NoIncognita = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        Res = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 255, 204));
        setPreferredSize(new java.awt.Dimension(800, 560));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Ingrese el número de puntos:");
        add(jLabel2);
        jLabel2.setBounds(20, 120, 220, 23);

        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jButton2.setText("Cargar puntos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(250, 210, 120, 40);

        textFieldNoPuntos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textFieldNoPuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNoPuntosActionPerformed(evt);
            }
        });
        add(textFieldNoPuntos);
        textFieldNoPuntos.setBounds(220, 110, 132, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Función:");
        add(jLabel5);
        jLabel5.setBounds(460, 440, 76, 17);

        jLabel1.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        jLabel1.setText("Método de Newton");
        add(jLabel1);
        jLabel1.setBounds(220, 20, 384, 61);

        textFieldValorX.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(textFieldValorX);
        textFieldValorX.setBounds(110, 220, 130, 30);

        jButton3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jButton3.setText("Vaciar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(270, 150, 94, 48);

        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jButton1.setText("Cargar tabla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(120, 150, 130, 48);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Tabla");
        add(jLabel4);
        jLabel4.setBounds(430, 80, 40, 20);

        X.setBackground(new java.awt.Color(153, 255, 204));
        X.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "   X"
            }
        ));
        X.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(X);

        add(jScrollPane1);
        jScrollPane1.setBounds(390, 110, 60, 160);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("El valor  de x evaluada en la funcion es:");
        add(jLabel6);
        jLabel6.setBounds(480, 460, 244, 30);

        textFieldResultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(textFieldResultado);
        textFieldResultado.setBounds(530, 490, 130, 30);

        Delta.setBackground(new java.awt.Color(255, 255, 153));
        Delta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "", ""
            }
        ));
        Delta.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(Delta);

        add(jScrollPane2);
        jScrollPane2.setBounds(10, 310, 430, 210);

        textFieldFuncion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(textFieldFuncion);
        textFieldFuncion.setBounds(550, 430, 200, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Tabla diferencias finitas");
        add(jLabel7);
        jLabel7.setBounds(150, 290, 160, 17);

        Y.setBackground(new java.awt.Color(153, 255, 204));
        Y.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "    Y"
            }
        ));
        jScrollPane3.setViewportView(Y);

        add(jScrollPane3);
        jScrollPane3.setBounds(450, 110, 60, 160);

        SG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        SG.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane4.setViewportView(SG);

        add(jScrollPane4);
        jScrollPane4.setBounds(540, 130, 200, 100);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Sistema de ecuaciones generado");
        add(jLabel8);
        jLabel8.setBounds(540, 110, 200, 17);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Solución");
        add(jLabel9);
        jLabel9.setBounds(610, 250, 76, 17);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("X a evaluar:");
        add(jLabel10);
        jLabel10.setBounds(20, 230, 76, 17);

        NoIncognita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "a"
            }
        ));
        jScrollPane5.setViewportView(NoIncognita);

        add(jScrollPane5);
        jScrollPane5.setBounds(570, 270, 70, 140);

        Res.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Valor"
            }
        ));
        jScrollPane6.setViewportView(Res);

        add(jScrollPane6);
        jScrollPane6.setBounds(640, 270, 70, 140);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
                    DiferenciasFinitas();
                    
                    Newton();
                    
                    textFieldValorX.setEditable(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Datos inválidos");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void textFieldNoPuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNoPuntosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNoPuntosActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        textFieldNoPuntos.setText(null);
        textFieldFuncion.setText(null);
        textFieldResultado.setText(null);
        textFieldValorX.setText(null);
        textFieldValorX.setEnabled(false);
        ecuacion = null;
        for (int i = 0; i < X.getRowCount(); i++) {
            X.setValueAt(null, i, 0);
            for (int j = 1; j < X.getColumnCount(); j++) {
                X.setValueAt(null, i, j);
            }
        }
        for (int i = 0; i < Y.getRowCount(); i++) {
            Y.setValueAt(null, i, 0);
            for (int j = 1; j < Y.getColumnCount(); j++) {
                Y.setValueAt(null, i, j);
            }
        }
        for (int i = 0; i < Delta.getRowCount(); i++) {
            Delta.setValueAt(null, i, 0);
            for (int j = 1; j < Delta.getColumnCount(); j++) {
                Delta.setValueAt(null, i, j);
            }
        }
        for (int i = 0; i < SG.getRowCount(); i++) {
            SG.setValueAt(null, i, 0);
            for (int j = 1; j < SG.getColumnCount(); j++) {
                SG.setValueAt(null, i, j);
            }
        }
        for (int i = 0; i < Res.getRowCount(); i++) {
            Res.setValueAt(null, i, 0);
            for (int j = 1; j < Res.getColumnCount(); j++) {
                Res.setValueAt(null, i, j);
            }
        }
        for (int i = 0; i < NoIncognita.getRowCount(); i++) {
            NoIncognita.setValueAt(null, i, 0);
            for (int j = 1; j < NoIncognita.getColumnCount(); j++) {
                NoIncognita.setValueAt(null, i, j);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if (textFieldNoPuntos.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "No ha ingresado dato.");
            } else {

                m = Integer.parseInt(textFieldNoPuntos.getText());
                if (m < 0) {

                    JOptionPane.showMessageDialog(null, "ingresa un dato valido.");
                }

                Object[][] M = new Object[m][1];
                Object[][] N = new Object[m][(m - 1)];
                Object[][] O = new Object[(m - 2)][(m - 1)];
                Object[][] NoIncognitas = new Object[(m - 2)][1];
                String[] EncabezadoTDF = new String[(m - 1)];
                String[] EncabezadoSG = new String[(m - 1)];

                for (int i = 2; i < EncabezadoTDF.length; i++) {
                    EncabezadoTDF[i] = "A^" + (i - 1) + "y(i)";
                }
                EncabezadoTDF[0] = "x(i)";
                EncabezadoTDF[1] = "y(i)";
                for (int i = 0; i < (EncabezadoSG.length - 1); i++) {
                    EncabezadoSG[i] = "a" + (i + 1);
                }
                EncabezadoSG[(m - 2)] = "Valor";

                for (int i = 0; i < m; i++) {
                    M[i][0] = null;
                }

                for (int i = 0; i < m; i++) {
                    for (int j = 0; j < (m - 1); j++) {
                        N[i][j] = null;
                    }
                }

                for (int i = 0; i < (m - 2); i++) {
                    for (int j = 0; j < (m - 1); j++) {
                        O[i][j] = null;
                    }
                }

                for (int i = 0; i < (m - 2); i++) {
                    NoIncognitas[i][0] = null;
                }

                X.setModel(new DefaultTableModel(M, new String[]{"x(i)"}));
               

                Y.setModel(new DefaultTableModel(M, new String[]{"y(i)"}));
                

                Delta.setModel(new DefaultTableModel(N, EncabezadoTDF));
                
                Delta.disable();

                SG.setModel(new DefaultTableModel(O, EncabezadoSG));
                
                SG.disable();

                NoIncognita.setModel(new DefaultTableModel(NoIncognitas, new String[]{"a"}));
               

                for (int i = 0; i < (m - 2); i++) {
                    NoIncognita.setValueAt((i + 1), i, 0);
                }
                NoIncognita.disable();

                Res.setModel(new DefaultTableModel(NoIncognitas, new String[]{"Valor"}));
                
                Res.disable();

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Favor de introducir valores validos");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void DiferenciasFinitas() {
        String ecua="";
        int Potencia = 0, Grado = (m - 3);
        double delta[][] = new double[m][m], x[] = new double[m], M[][] = new double[Grado + 1][Grado + 2], res[] = new double[Grado + 1];
        x = Matriz.CopiaVector(X, x, m);
        for (int i = 0; i < m; i++) {
            delta[i][0] = Double.parseDouble(String.valueOf(Y.getValueAt(i, 0)));
        }
        for (int j = 1; j <= (m - 1); j++) {
            for (int i = 0; i < m - j; i++) {
                delta[i][j] = delta[i + 1][j - 1] - delta[i][j - 1];
            }
        }
        for (int i = 0; i < (Grado + 1); i++) {
            Potencia = Grado;
            for (int j = 0; j < (Grado + 1); j++) {
                M[i][j] = Math.pow(x[i], Potencia);
                Potencia--;
            }
            M[i][(Grado + 1)] = delta[i][0];
        }
        res = SistemaEcuacion.Cramer(M, (Grado + 1), (Grado + 2));
        Potencia = Grado;
        for (int j = 0; j < Grado; j++) {
            if (res[j] < 0 || j == 0) {
                ecua += res[j] + "x^" + Potencia;
            } else if (res[j] > 0) {
                ecua += "+" + res[j] + "x^" + Potencia;
            }
            Potencia--;
        }
        if (res[Grado] < 0) {
            ecua += res[Grado];
        } else if (res[Grado] > 0) {
            ecua += "+" + res[Grado];
        }
        for (int i = 0; i < m; i++) {
            Delta.setValueAt(Double.parseDouble(String.valueOf(X.getValueAt(i, 0))), i, 0);
        }
        for (int i = 0; i < m; i++) {
            Delta.setValueAt(Double.parseDouble(String.valueOf(Y.getValueAt(i, 0))), i, 1);
        }

        for (int i = 0; i < m; i++) {
            for (int j = 2; j < (m - 1); j++) {
                Delta.setValueAt(delta[i][j - 1], i, j);
            }
        }
        SG = Matriz.Copia(M, SG, (Grado + 1), (Grado + 2));
        Res = Matriz.CopiaVector(res, Res, (Grado + 1));
        
        textFieldFuncion.setText(ecua);
        

    }

    public void Newton() {
        int Grado = (m - 3);
        double Abscisa = 0, Ordenada = 0, K = 0;
        double x[] = new double[m];
        x = Matriz.CopiaVector(X, x, m);
        Abscisa = Double.parseDouble(textFieldValorX.getText());
        Ordenada = 0;
        K = (Abscisa - x[0]) / (x[1] - x[0]);
        for (int i = 1; i <= (m - 2); i++) {
            double Num = 1, j = 0;
            while (j <= i - 2) {
                Num = Num * (K - j);
                j++;
            }
            Ordenada = Ordenada + ((Num) * (Double.parseDouble(String.valueOf(Delta.getValueAt(0, (i)))))) / (Factorial.Factorial((i - 1)));
        }
        textFieldResultado.setText(String.valueOf(Ordenada));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Delta;
    private javax.swing.JTable NoIncognita;
    private javax.swing.JTable Res;
    private javax.swing.JTable SG;
    private javax.swing.JTable X;
    private javax.swing.JTable Y;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField textFieldFuncion;
    private javax.swing.JTextField textFieldNoPuntos;
    private javax.swing.JTextField textFieldResultado;
    private javax.swing.JTextField textFieldValorX;
    // End of variables declaration//GEN-END:variables
}
