/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazgraficametodos;

/**
 *
 * @author Héctor
 */
import java.text.DecimalFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class PanelSimpsonFuncion extends javax.swing.JPanel {

    /**
     * Creates new form PanelSimpsonFuncion
     */
    Ecuacion ecu = new Ecuacion();

    public PanelSimpsonFuncion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        resul = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ff = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 255, 204));
        setPreferredSize(new java.awt.Dimension(800, 560));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Tabla resultante");
        add(jLabel2);
        jLabel2.setBounds(630, 120, 100, 17);

        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.setDragEnabled(true);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1);
        jTextField1.setBounds(410, 110, 140, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Ingrese valor de a:");
        add(jLabel3);
        jLabel3.setBounds(180, 180, 120, 17);

        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        add(jTextField2);
        jTextField2.setBounds(410, 170, 140, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Ingrese valor de b:");
        add(jLabel5);
        jLabel5.setBounds(180, 230, 116, 17);

        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        add(jTextField4);
        jTextField4.setBounds(410, 220, 140, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Ingrese número de puntos:");
        add(jLabel6);
        jLabel6.setBounds(180, 280, 167, 17);

        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });
        add(jTextField5);
        jTextField5.setBounds(410, 270, 140, 30);

        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(70, 350, 220, 80);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Valor de área aproximada de la función dentro del rango :");
        add(jLabel7);
        jLabel7.setBounds(210, 450, 390, 17);

        resul.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(resul);
        resul.setBounds(280, 480, 210, 30);

        jLabel1.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        jLabel1.setText("             Método de Simpson Función");
        add(jLabel1);
        jLabel1.setBounds(10, 30, 700, 30);

        ff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(ff);

        add(jScrollPane1);
        jScrollPane1.setBounds(580, 150, 190, 310);

        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton2.setText("Vaciar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(320, 350, 220, 80);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Ingrese ecuación:");
        add(jLabel4);
        jLabel4.setBounds(180, 120, 109, 17);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed

    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        char c = evt.getKeyChar();
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped

    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField5KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Ecuacion ecu = new Ecuacion();
            DecimalFormat D = new DecimalFormat("0.000");
            double X, area, y[], h;
            String funcion = jTextField1.getText();
            double a = Double.parseDouble(jTextField2.getText());
            double b = Double.parseDouble(jTextField4.getText());
            int n = Integer.parseInt(jTextField5.getText());
            DefaultTableModel modelo = new DefaultTableModel();

            double x[], my[];

            if (b <= a) {
                JOptionPane.showMessageDialog(null, "Rango inválido");
            } else if (n < 3 || n % 2 == 0) {
                JOptionPane.showMessageDialog(null, "Puntos pares, ingreselos de nuevo");
            } else {
                x = new double[n];
                y = new double[n];
                int m[] = new int[n];
                my = new double[n];
                m[0] = 1;
                m[n - 1] = 1;
                for (int i = 1; i < m.length - 1; i++) {
                    if ((i + 1) % 2 == 0) {
                        m[i] = 4;
                    } else {
                        m[i] = 2;
                    }

                }
                h = (b - a) / ((double) n - 1);
                X = a;
                for (int i = 0; i < n; i++) {
                    x[i] = X;
                    y[i] = ecu.ecuacion(funcion, x[i]);
                    X = X + h;
                }

                area = y[0] + y[n - 1];
                my[0] = y[0];
                my[n - 1] = y[n - 1];
                for (int i = 1; i < n - 1; i++) {
                    if ((i + 1) % 2 == 0) {
                        my[i] = 4 * y[i];
                        area = area + my[i];
                    } else {
                        my[i] = 2 * y[i];
                        area = area + my[i];
                    }
                }
                Vector valoresX = new Vector();
                Vector valoresY = new Vector();
                Vector valoresM = new Vector();
                Vector valoresMY = new Vector();
                for (int i = 0; i < n; i++) {
                    valoresX.add(D.format(x[i]));
                    valoresY.add(D.format(y[i]));
                    valoresM.add(m[i]);
                    valoresMY.add(D.format(my[i]));
                    //System.out.println(D.format(x[i]) + "\t" + D.format(y[i]) + "\t" + m[i] + "\t" + D.format(my[i]));
                }
                modelo.addColumn("X", valoresX);
                modelo.addColumn("Y", valoresY);
                modelo.addColumn("M", valoresM);
                modelo.addColumn("M*Y", valoresMY);
                ff.setModel(modelo);
                ff.updateUI();
                area = area * (h / 3);
                String s = "";
                s += "" + D.format(area);
                resul.setText(s);
                Funcion f = new Funcion(funcion, "Grafica de la función del método de simpson");
            }

         
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Favor de introducir valores validos");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            resul.setText("");
            for (int i = 0; i < ff.getRowCount(); i++) {

                ff.setValueAt(null, i, 0);
                for (int j = 1; j < ff.getColumnCount(); j++) {

                    ff.setValueAt(null, i, j);

                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Los elementos están vacíos");
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ff;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField resul;
    // End of variables declaration//GEN-END:variables
}
