/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazgraficametodos;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Héctor
 */
public class PanelIterativo extends javax.swing.JPanel {

    /**
     * Creates new form PanelIterativo
     */
    Metodos metodo = new Metodos();
    public PanelIterativo() {
        initComponents();
         jacobi.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        incognitas = new javax.swing.JTextField();
        jacobi = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        textError = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaJacobi = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        iter = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jr = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 255, 204));
        setPreferredSize(new java.awt.Dimension(800, 560));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Ingrese el número de incógnitas:");
        add(jLabel2);
        jLabel2.setBounds(30, 150, 220, 23);

        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(550, 320, 100, 40);

        incognitas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        incognitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incognitasActionPerformed(evt);
            }
        });
        add(incognitas);
        incognitas.setBounds(250, 143, 132, 30);

        jacobi.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jacobi.setText("Jacobi");
        jacobi.setOpaque(false);
        jacobi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jacobiActionPerformed(evt);
            }
        });
        add(jacobi);
        jacobi.setBounds(250, 100, 79, 29);

        jRadioButton2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jRadioButton2.setText("Gauss-Seidel");
        jRadioButton2.setOpaque(false);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        add(jRadioButton2);
        jRadioButton2.setBounds(420, 100, 170, 29);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Ingrese el error permisible:");
        add(jLabel5);
        jLabel5.setBounds(30, 200, 171, 17);

        jLabel1.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        jLabel1.setText("Métodos iterativos");
        add(jLabel1);
        jLabel1.setBounds(220, 20, 392, 61);

        textError.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(textError);
        textError.setBounds(250, 185, 130, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Resultados");
        add(jLabel3);
        jLabel3.setBounds(570, 380, 67, 17);

        jButton3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jButton3.setText("Vaciar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(230, 280, 94, 48);

        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(130, 280, 90, 48);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Matriz propuesta");
        add(jLabel4);
        jLabel4.setBounds(540, 150, 104, 17);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane4.setViewportView(jTextArea1);

        add(jScrollPane4);
        jScrollPane4.setBounds(510, 400, 183, 114);

        tablaJacobi.setBackground(new java.awt.Color(204, 255, 204));
        tablaJacobi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "A", "B", "C", "Result"
            }
        ));
        tablaJacobi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tablaJacobi);

        add(jScrollPane1);
        jScrollPane1.setBounds(490, 180, 219, 132);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Ingrese número de iteraciones:");
        add(jLabel6);
        jLabel6.setBounds(30, 240, 200, 17);

        iter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(iter);
        iter.setBounds(250, 230, 130, 30);

        jr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        jScrollPane2.setViewportView(jr);

        add(jScrollPane2);
        jScrollPane2.setBounds(40, 370, 360, 170);
    }// </editor-fold>//GEN-END:initComponents
    int inco;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if(jacobi.isSelected()){
            metodo.jacobi(inco, tablaJacobi, incognitas, textError, iter, jTextArea1, jr);
        }else if(jRadioButton2.isSelected()){
            metodo.seidel(inco, tablaJacobi, incognitas, textError,iter, jTextArea1, jr);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void incognitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incognitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_incognitasActionPerformed

    private void jacobiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jacobiActionPerformed
        // TODO add your handling code here:
        jacobi.setSelected(true);
        jRadioButton2.setSelected(false);
    }//GEN-LAST:event_jacobiActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        jacobi.setSelected(false);
        jRadioButton2.setSelected(true);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            incognitas.setText("");
            jTextArea1.setText("");
            textError.setText("");
            iter.setText("");
            for (int i = 0; i < tablaJacobi.getRowCount(); i++) {
                tablaJacobi.setValueAt(null, i, 0);
                for (int j = 1; j < tablaJacobi.getColumnCount(); j++) {
                    tablaJacobi.setValueAt(null, i, j);
                }
            }
            
            for (int i = 0; i < jr.getRowCount(); i++) {
                jr.setValueAt(null, i, 0);
                for (int j = 1; j < jr.getColumnCount(); j++) {
                    jr.setValueAt(null, i, j);
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Los elementos están vacíos");
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    DefaultTableModel modelo;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            inco = Integer.parseInt(incognitas.getText());
            modelo = new DefaultTableModel();
            modelo.setRowCount(inco);
            modelo.setColumnCount(inco + 1);
            tablaJacobi.setModel(modelo);
            tablaJacobi.updateUI();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Favor de introducir valores validos");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField incognitas;
    private javax.swing.JTextField iter;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JRadioButton jacobi;
    private javax.swing.JTable jr;
    private javax.swing.JTable tablaJacobi;
    private javax.swing.JTextField textError;
    // End of variables declaration//GEN-END:variables
}
