/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazgraficametodos;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Héctor
 */
public class Principal extends javax.swing.JFrame {

    JPanel contenido;
    PanelInicio pi;
    PanelNoIterativo pI;
    PanelNewton pn;
    PanelLagrange pg;
    PanelLimites pl;
    PanelSimpsonFuncion psf;
    PanelSimpsonTabla pst;
    PanelTrapFuncion ptf;
    PanelTrapTabla ptt;
    PanelMinimos pm;
    PanelFinitas pf;

    PanelIterativo pnI;
    Metodos metodo = new Metodos();

    public Principal() {
        initComponents();
        this.setResizable(false);
        contenido = new JPanel();

        pf = new PanelFinitas();
        pf.setVisible(false);
        contenido.add(pf);
        
        pm = new PanelMinimos();
        pm.setVisible(false);
        contenido.add(pm);
        
        ptt = new PanelTrapTabla();
        ptt.setVisible(false);
        contenido.add(ptt);
        
        ptf = new PanelTrapFuncion();
        ptf.setVisible(false);
        contenido.add(ptf);

        pst = new PanelSimpsonTabla();
        pst.setVisible(false);
        contenido.add(pst);

        psf = new PanelSimpsonFuncion();
        psf.setVisible(false);
        contenido.add(psf);

        pl = new PanelLimites();
        pl.setVisible(false);
        contenido.add(pl);

        pg = new PanelLagrange();
        pg.setVisible(false);
        contenido.add(pg);

        pn = new PanelNewton();
        pn.setVisible(false);
        contenido.add(pn);

        pi = new PanelInicio();
        pi.setVisible(true);
        contenido.add(pi);

        pI = new PanelNoIterativo();
        pI.setVisible(false);
        contenido.add(pI);

        pnI = new PanelIterativo();
        pnI.setVisible(false);
        contenido.add(pnI);

        panelRaices.setVisible(false);

        contenido.setSize(800, 600);
        contenido.setVisible(true);
        this.setSize(800, 600);
        add(contenido);

        inicio.setEnabled(false);

        Salir salir = new Salir();
        addWindowListener(salir);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        panelRaices = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        panelFuncion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaBiseccion = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        inicio = new javax.swing.JMenu();
        ini = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMenuItem11 = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();

        jMenuItem18.setText("jMenuItem18");

        jMenuItem19.setText("jMenuItem19");

        jMenuItem20.setText("jMenuItem20");

        jMenu8.setText("jMenu8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Métodos numéricos");
        setBackground(new java.awt.Color(51, 255, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        panelRaices.setBackground(new java.awt.Color(153, 255, 153));
        panelRaices.setForeground(new java.awt.Color(153, 153, 255));
        panelRaices.setPreferredSize(new java.awt.Dimension(850, 630));
        panelRaices.setLayout(null);

        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton2.setText("Vaciar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelRaices.add(jButton2);
        jButton2.setBounds(210, 290, 75, 27);

        panelFuncion.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelFuncionLayout = new javax.swing.GroupLayout(panelFuncion);
        panelFuncion.setLayout(panelFuncionLayout);
        panelFuncionLayout.setHorizontalGroup(
            panelFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelFuncionLayout.setVerticalGroup(
            panelFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        panelRaices.add(panelFuncion);
        panelFuncion.setBounds(370, 290, 400, 230);

        jLabel1.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        jLabel1.setText("             Método de Bisección");
        panelRaices.add(jLabel1);
        jLabel1.setBounds(0, 10, 850, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Ingrese ecuación:");
        panelRaices.add(jLabel2);
        jLabel2.setBounds(30, 80, 109, 17);

        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        panelRaices.add(jTextField3);
        jTextField3.setBounds(280, 150, 60, 20);

        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.setDragEnabled(true);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        panelRaices.add(jTextField1);
        jTextField1.setBounds(220, 76, 120, 20);

        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        panelRaices.add(jTextField4);
        jTextField4.setBounds(280, 190, 60, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Ingrese punto a:");
        panelRaices.add(jLabel3);
        jLabel3.setBounds(30, 120, 102, 17);

        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });
        panelRaices.add(jTextField5);
        jTextField5.setBounds(280, 230, 60, 20);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Ingrese punto b:");
        panelRaices.add(jLabel4);
        jLabel4.setBounds(30, 150, 102, 17);

        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelRaices.add(jButton1);
        jButton1.setBounds(90, 290, 85, 27);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Ingrese error permitido:");
        panelRaices.add(jLabel5);
        jLabel5.setBounds(30, 190, 151, 17);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("La raíz buscada es:");
        panelRaices.add(jLabel7);
        jLabel7.setBounds(40, 420, 117, 17);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Ingrese número de iteraciones:");
        panelRaices.add(jLabel6);
        jLabel6.setBounds(30, 230, 193, 17);

        jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelRaices.add(jTextField6);
        jTextField6.setBounds(190, 406, 160, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Gráfica");
        panelRaices.add(jLabel8);
        jLabel8.setBounds(540, 270, 45, 17);

        tablaBiseccion.setBackground(new java.awt.Color(153, 255, 255));
        tablaBiseccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", "", ""
            }
        ));
        jScrollPane2.setViewportView(tablaBiseccion);

        panelRaices.add(jScrollPane2);
        jScrollPane2.setBounds(360, 50, 430, 210);

        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        panelRaices.add(jTextField2);
        jTextField2.setBounds(280, 116, 60, 20);

        getContentPane().add(panelRaices);
        panelRaices.setBounds(0, 0, 920, 600);

        inicio.setText("Inicio");
        inicio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        inicio.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });

        ini.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        ini.setForeground(new java.awt.Color(0, 153, 153));
        ini.setText("Mostrar");
        ini.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniActionPerformed(evt);
            }
        });
        inicio.add(ini);

        jMenuBar1.add(inicio);

        jMenu2.setText("Raices de ecuaciones");
        jMenu2.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem10.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jMenuItem10.setForeground(new java.awt.Color(0, 153, 153));
        jMenuItem10.setText("Método de Bisección");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);
        jMenu2.add(jSeparator1);

        jMenuItem9.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jMenuItem9.setForeground(new java.awt.Color(0, 153, 153));
        jMenuItem9.setText("Método de Falsa Posición");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);
        jMenu2.add(jSeparator3);

        jMenuItem8.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jMenuItem8.setForeground(new java.awt.Color(0, 153, 153));
        jMenuItem8.setText("Método de Secante");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);
        jMenu2.add(jSeparator4);

        jMenuItem5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jMenuItem5.setForeground(new java.awt.Color(0, 153, 153));
        jMenuItem5.setText("Método de Aproximaciones Sucesivas");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);
        jMenu2.add(jSeparator5);

        jMenuItem7.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jMenuItem7.setForeground(new java.awt.Color(0, 153, 153));
        jMenuItem7.setText("Metodo de Newton-Raphson");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);
        jMenu2.add(jSeparator7);

        jMenuItem6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jMenuItem6.setForeground(new java.awt.Color(0, 153, 153));
        jMenuItem6.setText("Método de Newton 2do Orden");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Sistemas de ecuaciones");
        jMenu1.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jMenuItem1.setForeground(new java.awt.Color(0, 153, 153));
        jMenuItem1.setText("Métodos no iterativos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator6);

        jMenuItem2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jMenuItem2.setForeground(new java.awt.Color(0, 153, 153));
        jMenuItem2.setText("Métodos iterativos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Interpolación");
        jMenu3.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N

        jMenuItem4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jMenuItem4.setForeground(new java.awt.Color(0, 153, 153));
        jMenuItem4.setText("Método de Newton");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);
        jMenu3.add(jSeparator8);

        jMenuItem3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jMenuItem3.setForeground(new java.awt.Color(0, 153, 153));
        jMenuItem3.setText("Método de Lagrange");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);
        jMenu3.add(jSeparator9);

        jMenuItem11.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jMenuItem11.setForeground(new java.awt.Color(0, 153, 153));
        jMenuItem11.setText("Método de Diferencias finitas");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);
        jMenu3.add(jSeparator10);

        jMenuItem12.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jMenuItem12.setForeground(new java.awt.Color(0, 153, 153));
        jMenuItem12.setText("Método de Mínimos cuadrados");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem12);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Diferenciación");
        jMenu4.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N

        jMenuItem13.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jMenuItem13.setForeground(new java.awt.Color(0, 153, 153));
        jMenuItem13.setText("Método de limites");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem13);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Integración numérica");
        jMenu5.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N

        jMenu6.setForeground(new java.awt.Color(0, 153, 153));
        jMenu6.setText("Método de Simpson");
        jMenu6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N

        jMenuItem14.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 10)); // NOI18N
        jMenuItem14.setForeground(new java.awt.Color(0, 153, 153));
        jMenuItem14.setText("Tabla");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem14);

        jMenuItem15.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 10)); // NOI18N
        jMenuItem15.setForeground(new java.awt.Color(0, 153, 153));
        jMenuItem15.setText("Función");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem15);

        jMenu5.add(jMenu6);

        jMenu7.setForeground(new java.awt.Color(0, 153, 153));
        jMenu7.setText("Método de Trapecio");
        jMenu7.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N

        jMenuItem16.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 10)); // NOI18N
        jMenuItem16.setForeground(new java.awt.Color(0, 153, 153));
        jMenuItem16.setText("Tabla");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem16);

        jMenuItem17.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 10)); // NOI18N
        jMenuItem17.setForeground(new java.awt.Color(0, 153, 153));
        jMenuItem17.setText("Función");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem17);

        jMenu5.add(jMenu7);

        jMenuBar1.add(jMenu5);

        jMenu9.setText("Ecuaciones diferenciales");
        jMenu9.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed

    }//GEN-LAST:event_inicioActionPerformed
    class Salir extends WindowAdapter {

        @Override
        public void windowClosing(WindowEvent e) {
            JFrame mv = (JFrame) e.getSource();
            if (JOptionPane.YES_OPTION == JOptionPane.showConfirmDialog(null, "¿Seguro que desea salir?", "Metodos Numéricos", JOptionPane.YES_NO_OPTION)) {
                mv.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            }
        }

    }
    private void iniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniActionPerformed
        inicio.setEnabled(false);
        pi.setVisible(true);
        pI.setVisible(false);
        pnI.setVisible(false);
        pn.setVisible(false);
        pg.setVisible(false);
        pl.setVisible(false);
        psf.setVisible(false);
        pst.setVisible(false);
        ptf.setVisible(false);
        ptt.setVisible(false);
        pm.setVisible(false);
        pf.setVisible(false);
        
        panelRaices.setVisible(false);
        jMenuItem10.setEnabled(true);
        jMenuItem9.setEnabled(true);
        jMenuItem8.setEnabled(true);
        jMenuItem7.setEnabled(true);
        jMenuItem6.setEnabled(true);
        jMenuItem5.setEnabled(true);
    }//GEN-LAST:event_iniActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        inicio.setEnabled(true);
        pi.setVisible(false);
        pI.setVisible(true);
        pnI.setVisible(false);
        pn.setVisible(false);
        pl.setVisible(false);
        pg.setVisible(false);
        psf.setVisible(false);
        pst.setVisible(false);
        ptf.setVisible(false);
        ptt.setVisible(false);
        pm.setVisible(false);
        pf.setVisible(false);
        
        panelRaices.setVisible(false);
        jMenuItem10.setEnabled(true);
        jMenuItem9.setEnabled(true);
        jMenuItem8.setEnabled(true);
        jMenuItem7.setEnabled(true);
        jMenuItem6.setEnabled(true);
        jMenuItem5.setEnabled(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        inicio.setEnabled(true);
        pi.setVisible(false);
        pI.setVisible(false);
        pnI.setVisible(true);
        pn.setVisible(false);
        pg.setVisible(false);
        psf.setVisible(false);
        pst.setVisible(false);
        ptf.setVisible(false);
        ptt.setVisible(false);
        pm.setVisible(false);
        pf.setVisible(false);
        
        panelRaices.setVisible(false);
        jMenuItem10.setEnabled(true);
        jMenuItem9.setEnabled(true);
        jMenuItem8.setEnabled(true);
        jMenuItem7.setEnabled(true);
        jMenuItem6.setEnabled(true);
        jMenuItem5.setEnabled(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");

            panelFuncion.removeAll();
            panelFuncion.repaint();
            for (int i = 0; i < tablaBiseccion.getRowCount(); i++) {

                tablaBiseccion.setValueAt(null, i, 0);
                for (int j = 1; j < tablaBiseccion.getColumnCount(); j++) {

                    tablaBiseccion.setValueAt(null, i, j);

                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Los elementos están vacíos");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        char c = evt.getKeyChar();
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped

    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField5KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (!jMenuItem10.isEnabled()) {
            metodo.biseccion(jTextField1, jTextField2, jTextField3, jTextField4, jTextField5, tablaBiseccion, jTextField6, panelFuncion);
        } else if (!jMenuItem9.isEnabled()) {
            metodo.falsaPosicion(jTextField1, jTextField2, jTextField3, jTextField4, jTextField5, tablaBiseccion, jTextField6, panelFuncion);
        } else if (!jMenuItem8.isEnabled()) {
            metodo.secante(jTextField1, jTextField2, jTextField3, jTextField4, jTextField5, tablaBiseccion, jTextField6, panelFuncion);
        } else if (!jMenuItem7.isEnabled()) {
            metodo.newton1(jTextField1, jTextField2, jTextField4, jTextField5, tablaBiseccion, jTextField6, panelFuncion);
        } else if (!jMenuItem5.isEnabled()) {
            metodo.aproximaciones(jTextField1, jTextField2, jTextField4, jTextField5, tablaBiseccion, jTextField6, panelFuncion);
        } else if (!jMenuItem6.isEnabled()) {
            metodo.newton2(jTextField1, jTextField2, jTextField4, jTextField5, tablaBiseccion, jTextField6, panelFuncion);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed

    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        char c = evt.getKeyChar();
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        panelRaices.setVisible(true);
        jMenuItem10.setEnabled(true);
        jMenuItem9.setEnabled(true);
        jMenuItem8.setEnabled(false);
        jMenuItem7.setEnabled(true);
        jMenuItem6.setEnabled(true);
        jMenuItem5.setEnabled(true);

        inicio.setEnabled(true);
        pi.setVisible(false);
        pI.setVisible(false);
        pnI.setVisible(false);
        pn.setVisible(false);
        psf.setVisible(false);
        pg.setVisible(false);
        pl.setVisible(false);
        pst.setVisible(false);
        ptf.setVisible(false);
        ptt.setVisible(false);
        pm.setVisible(false);
        pf.setVisible(false);

        jLabel1.setText("   Método de secante");
        jLabel3.setText("Ingrese X1:");
        jLabel4.setVisible(true);
        jLabel4.setText("Ingrese X1+1:");
        jTextField3.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        panelRaices.setVisible(true);
        jMenuItem10.setEnabled(true);
        jMenuItem9.setEnabled(false);
        jMenuItem8.setEnabled(true);
        jMenuItem7.setEnabled(true);
        jMenuItem6.setEnabled(true);
        jMenuItem5.setEnabled(true);

        inicio.setEnabled(true);
        pi.setVisible(false);
        pI.setVisible(false);
        pnI.setVisible(false);
        pn.setVisible(false);
        pg.setVisible(false);
        pl.setVisible(false);
        psf.setVisible(false);
        pst.setVisible(false);
        ptf.setVisible(false);
        ptt.setVisible(false);
        pm.setVisible(false);
        pf.setVisible(false);

        jLabel1.setText("   Método de falsa posición");
        jLabel3.setText("Ingrese Xi:");
        jLabel4.setVisible(true);
        jLabel4.setText("Ingrese X1:");
        jTextField3.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        panelRaices.setVisible(true);
        jMenuItem10.setEnabled(false);
        jMenuItem9.setEnabled(true);
        jMenuItem8.setEnabled(true);
        jMenuItem7.setEnabled(true);
        jMenuItem6.setEnabled(true);
        jMenuItem5.setEnabled(true);

        inicio.setEnabled(true);
        pi.setVisible(false);
        pI.setVisible(false);
        pnI.setVisible(false);
        pn.setVisible(false);
        pg.setVisible(false);
        pl.setVisible(false);
        psf.setVisible(false);
        pst.setVisible(false);
        ptf.setVisible(false);
        ptt.setVisible(false);
        pm.setVisible(false);
        pf.setVisible(false);

        jLabel1.setText("   Método de bisección");
        jLabel3.setText("Ingrese punto a:");
        jLabel4.setVisible(true);
        jLabel4.setText("Ingrese punto b:");
        jTextField3.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        panelRaices.setVisible(true);
        jMenuItem10.setEnabled(true);
        jMenuItem9.setEnabled(true);
        jMenuItem8.setEnabled(true);
        jMenuItem7.setEnabled(false);
        jMenuItem6.setEnabled(true);
        jMenuItem5.setEnabled(true);

        inicio.setEnabled(true);
        pi.setVisible(false);
        pI.setVisible(false);
        pnI.setVisible(false);
        pn.setVisible(false);
        pg.setVisible(false);
        pl.setVisible(false);
        psf.setVisible(false);
        pst.setVisible(false);
        ptf.setVisible(false);
        ptt.setVisible(false);
        pm.setVisible(false);
        pf.setVisible(false);

        jLabel1.setText("   Método de Newton-Raphson");
        jLabel3.setText("Xi:");
        jLabel4.setVisible(false);
        jTextField3.setVisible(false);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        panelRaices.setVisible(true);
        jMenuItem10.setEnabled(true);
        jMenuItem9.setEnabled(true);
        jMenuItem8.setEnabled(true);
        jMenuItem7.setEnabled(true);
        jMenuItem6.setEnabled(true);
        jMenuItem5.setEnabled(false);

        inicio.setEnabled(true);
        pi.setVisible(false);
        pI.setVisible(false);
        pnI.setVisible(false);
        pn.setVisible(false);
        pg.setVisible(false);
        pl.setVisible(false);
        psf.setVisible(false);
        pst.setVisible(false);
        ptf.setVisible(false);
        ptt.setVisible(false);
        pm.setVisible(false);
        pf.setVisible(false);
        jLabel1.setText("   Método de Aproximaciones sucesivas");
        jLabel3.setText("X0:");
        jLabel4.setVisible(false);
        jTextField3.setVisible(false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        panelRaices.setVisible(true);
        jMenuItem10.setEnabled(true);
        jMenuItem9.setEnabled(true);
        jMenuItem8.setEnabled(true);
        jMenuItem7.setEnabled(true);
        jMenuItem6.setEnabled(false);
        jMenuItem5.setEnabled(true);

        inicio.setEnabled(true);
        pi.setVisible(false);
        pI.setVisible(false);
        pnI.setVisible(false);
        pn.setVisible(false);
        pg.setVisible(false);
        pl.setVisible(false);
        psf.setVisible(false);
        pst.setVisible(false);
        ptf.setVisible(false);
        ptt.setVisible(false);
        pf.setVisible(false);
        pm.setVisible(false);

        jLabel1.setText("   Método de Newton 2do Orden");
        jLabel3.setText("Xi:");
        jLabel4.setVisible(false);
        jTextField3.setVisible(false);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
        inicio.setEnabled(true);
        pi.setVisible(false);
        pI.setVisible(false);
        pnI.setVisible(false);
        pn.setVisible(false);
        pg.setVisible(false);
        pl.setVisible(false);
        psf.setVisible(false);
        pst.setVisible(false);
        ptf.setVisible(false);
        ptt.setVisible(true);
        pf.setVisible(false);
        pm.setVisible(false);
        panelRaices.setVisible(false);
        jMenuItem10.setEnabled(true);
        jMenuItem9.setEnabled(true);
        jMenuItem8.setEnabled(true);
        jMenuItem7.setEnabled(true);
        jMenuItem6.setEnabled(true);
        jMenuItem5.setEnabled(true);
        
        
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        inicio.setEnabled(true);
        pi.setVisible(false);
        pI.setVisible(false);
        pnI.setVisible(false);
        pn.setVisible(true);
        pg.setVisible(false);
        pl.setVisible(false);
        psf.setVisible(false);
        pst.setVisible(false);
        ptf.setVisible(false);
        ptt.setVisible(false);
        pm.setVisible(false);
        pf.setVisible(false);
        panelRaices.setVisible(false);
        jMenuItem10.setEnabled(true);
        jMenuItem9.setEnabled(true);
        jMenuItem8.setEnabled(true);
        jMenuItem7.setEnabled(true);
        jMenuItem6.setEnabled(true);
        jMenuItem5.setEnabled(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:

        inicio.setEnabled(true);
        pi.setVisible(false);
        pI.setVisible(false);
        pnI.setVisible(false);
        pn.setVisible(false);
        pg.setVisible(true);
        ptf.setVisible(false);
        pl.setVisible(false);
        psf.setVisible(false);
        pst.setVisible(false);
        ptt.setVisible(false);
        pf.setVisible(false);
        pm.setVisible(false);
        panelRaices.setVisible(false);
        jMenuItem10.setEnabled(true);
        jMenuItem9.setEnabled(true);
        jMenuItem8.setEnabled(true);
        jMenuItem7.setEnabled(true);
        jMenuItem6.setEnabled(true);
        jMenuItem5.setEnabled(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        inicio.setEnabled(true);
        pi.setVisible(false);
        pI.setVisible(false);
        pnI.setVisible(false);
        pn.setVisible(false);
        pg.setVisible(false);
        pl.setVisible(true);
        psf.setVisible(false);
        ptf.setVisible(false);
        pst.setVisible(false);
        ptt.setVisible(false);
        pm.setVisible(false);
        pf.setVisible(false);
        panelRaices.setVisible(false);
        jMenuItem10.setEnabled(true);
        jMenuItem9.setEnabled(true);
        jMenuItem8.setEnabled(true);
        jMenuItem7.setEnabled(true);
        jMenuItem6.setEnabled(true);
        jMenuItem5.setEnabled(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:

        inicio.setEnabled(true);
        pi.setVisible(false);
        pI.setVisible(false);
        pnI.setVisible(false);
        pn.setVisible(false);
        pg.setVisible(false);
        pl.setVisible(false);
        psf.setVisible(true);
        ptf.setVisible(false);
        pst.setVisible(false);
        ptt.setVisible(false);
        pm.setVisible(false);
        pf.setVisible(false);
        panelRaices.setVisible(false);
        jMenuItem10.setEnabled(true);
        jMenuItem9.setEnabled(true);
        jMenuItem8.setEnabled(true);
        jMenuItem7.setEnabled(true);
        jMenuItem6.setEnabled(true);
        jMenuItem5.setEnabled(true);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        inicio.setEnabled(true);
        pi.setVisible(false);
        pI.setVisible(false);
        pnI.setVisible(false);
        pn.setVisible(false);
        ptf.setVisible(false);
        pg.setVisible(false);
        pl.setVisible(false);
        psf.setVisible(false);
        pm.setVisible(false);
        pst.setVisible(true);
        ptt.setVisible(false);
        pf.setVisible(false);
        panelRaices.setVisible(false);
        jMenuItem10.setEnabled(true);
        jMenuItem9.setEnabled(true);
        jMenuItem8.setEnabled(true);
        jMenuItem7.setEnabled(true);
        jMenuItem6.setEnabled(true);
        jMenuItem5.setEnabled(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
        inicio.setEnabled(true);
        pi.setVisible(false);
        pI.setVisible(false);
        pnI.setVisible(false);
        pn.setVisible(false);
        ptf.setVisible(true);
        pg.setVisible(false);
        pl.setVisible(false);
        pm.setVisible(false);
        psf.setVisible(false);
        pst.setVisible(false);
        pf.setVisible(false);
        ptt.setVisible(false);
        panelRaices.setVisible(false);
        jMenuItem10.setEnabled(true);
        jMenuItem9.setEnabled(true);
        jMenuItem8.setEnabled(true);
        jMenuItem7.setEnabled(true);
        jMenuItem6.setEnabled(true);
        jMenuItem5.setEnabled(true);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        inicio.setEnabled(true);
        pi.setVisible(false);
        pI.setVisible(false);
        pnI.setVisible(false);
        pn.setVisible(false);
        ptf.setVisible(false);
        pg.setVisible(false);
        pf.setVisible(false);
        pl.setVisible(false);
        pm.setVisible(true);
        psf.setVisible(false);
        pst.setVisible(false);
        ptt.setVisible(false);
        panelRaices.setVisible(false);
        jMenuItem10.setEnabled(true);
        jMenuItem9.setEnabled(true);
        jMenuItem8.setEnabled(true);
        jMenuItem7.setEnabled(true);
        jMenuItem6.setEnabled(true);
        jMenuItem5.setEnabled(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        inicio.setEnabled(true);
        pi.setVisible(false);
        pI.setVisible(false);
        pnI.setVisible(false);
        pn.setVisible(false);
        ptf.setVisible(false);
        pg.setVisible(false);
        pf.setVisible(true);
        pl.setVisible(false);
        pm.setVisible(false);
        psf.setVisible(false);
        pst.setVisible(false);
        ptt.setVisible(false);
        panelRaices.setVisible(false);
        jMenuItem10.setEnabled(true);
        jMenuItem9.setEnabled(true);
        jMenuItem8.setEnabled(true);
        jMenuItem7.setEnabled(true);
        jMenuItem6.setEnabled(true);
        jMenuItem5.setEnabled(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Principal p = new Principal();
                p.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
                p.setVisible(true);

                p.setLocationRelativeTo(null);

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ini;
    private javax.swing.JMenu inicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JPanel panelFuncion;
    private javax.swing.JPanel panelRaices;
    private javax.swing.JTable tablaBiseccion;
    // End of variables declaration//GEN-END:variables
}
